### PR TITLE
Add quote about hug

### PR DESCRIPTION
**Pull request by SharoonRafeek**
Added two quotes about hugs.

### CODE REVIEW

**Comment by achasveachas** [comment]
It looks like this commit changed the spacing in the whole file. Please fix it so I can merge it.

**Comment by SharoonRafeek** [comment]
I have created a new commit with all the changes. Thanks.

**Review by achasveachas — APPROVED** [review]
Looks great! Thanks 🤗 

Let me know if you have a twitter handle so I can give you a shoutout.

**Comment by SharoonRafeek** [comment]
@Nasa_potd, It is also a Twitter bot. Thanks.

**Pull request merged**
