### PR TITLE
added some messages

### PR DESCRIPTION
**Pull request by Viennivre**
added about three quotes to #12

### CODE REVIEW

**Review by achasveachas — CHANGES_REQUESTED** [review]
Thanks @Viennivre! These are great!

Can you just add periods (".") to the ends of the sentences before I merge this?

**Comment by Viennivre** [comment]
> Thanks @Viennivre! These are great!
> 
> Can you just add periods (".") to the ends of the sentences before I merge this?

Sure, let me quickly do that.

**Review by achasveachas — APPROVED** [review]
Awesome! Thanks 🤗

Let me know if you have s Twitter handle so I can give you a shout-out!

**Comment by Viennivre** [comment]
> Awesome! Thanks 🤗
> 
> Let me know if you have s Twitter handle so I can give you a shout-out!

Yes I do , @viennivre is my twitter handle . Thanks 🤗

**Pull request merged**
