### PR TITLE
Splitting into modules, sorting imports and adding types

### PR DESCRIPTION
**Pull request by jamesrweb**

### CODE REVIEW

**Comment by jamesrweb** [comment]
Hi @achasveachas, i'm not sure what you mean by "the branch diverged", could you clarify? 😄

**Comment by jamesrweb** [comment]
You just want me to run `git rebase master` on the branch, just checking before I do so to be sure! 😉

**Comment by achasveachas** [comment]
Yes, and then fix any merge conflicts that might come up.

**Comment by jamesrweb** [comment]
@achasveachas rebased and pushed, should be reflected now, can you verify?

**Comment by jamesrweb** [comment]
Any updates @achasveachas?

**Pull request closed without merging**
